# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CCPColorSimulator2015' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  
	 use_frameworks!
	pod 'GPUImage'

  # Pods for CCPColorSimulator2015

  target 'CCPColorSimulator2015Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
